# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build Frontend

on:
  push:
    branches: [ "main", "dev" ]
    paths:
      - 'src/frontend/**/*.ts'
      - 'src/frontend/**/*.tsx'
      - 'src/frontend/**/*.js'
      - 'src/frontend/**/*.jsx'
      - 'src/frontend/**/*.json'
      - 'src/frontend/**/*.css'
      - 'src/frontend/**/*.scss'
      - 'src/frontend/**/*.html'
      - '.github/workflows/node.js.yml'
  pull_request:
    branches: [ "main", "dev" ]
    paths:
      - 'src/frontend/**/*.ts'
      - 'src/frontend/**/*.tsx'
      - 'src/frontend/**/*.js'
      - 'src/frontend/**/*.jsx'
      - 'src/frontend/**/*.json'
      - 'src/frontend/**/*.css'
      - 'src/frontend/**/*.scss'
      - 'src/frontend/**/*.html'
      - '.github/workflows/node.js.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/frontend
    strategy:
      matrix:
        node-version: [20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v6
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'src/frontend/package-lock.json'
    - run: npm ci
    - run: NODE_OPTIONS=--max_old_space_size=8192 npm run build --if-present
    - run: npm run test --if-present
